### ISSUE TITLE
debug_info isn't passed

### ISSUE THREAD

**Issue by musm** [kimikage/CodeCosts.jl#8]
Looks like it's not possible to pass `debug_info`  (actually looks like just a place holder right now? )

**Comment by kimikage** [comment]
To avoid re-implementing the code printer, I have decided not to parse the `CodeInfo`, but to qualify the printed text. Because of this "laziness", the current implementation suffers from line misalignments. I'm going to try to interpret `CodeInfo` a little more seriously.

**Comment by kimikage** [comment]
I saw the implementation of `CodeInfo` printer, then took a deep breath and decided to continue the "laziness". :sweat_smile:
